version: "3.9"

services:
  backend: &backend
    build:
      context: .
      dockerfile: docker/development/backend.Dockerfile
    image: backend:latest
    volumes:
      - ./backend:/backend:cached
      - backend_tmp:/backend/tmp
      - bundle:/backend/vendor
    command: bin/rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    logging:
      driver: none

  frontend:
    build:
      context: .
      dockerfile: docker/development/frontend.Dockerfile
    volumes:
      - ./frontend:/frontend:cached
      - node_modules:/frontend/node_modules
    command: yarn dev --port 3001 --host 0.0.0.0
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"

  redis:
    image: 'redis:7.0.11'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    image: backend:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ./backend:/backend:cached
      - bundle:/backend/vendor
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    env_file:
      - ./backend/.env

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"


volumes:
  bundle:
  db_data:
  node_modules:
  backend_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
  redis:
