version: "3.9"

services:
  backend: &backend
    build:
      context: .
      dockerfile: docker/production/backend.Dockerfile
    volumes:
      - ./backend:/backend:cached
      - backend_tmp:/backend/tmp
      - bundle:/backend/vendor
    command: bin/rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    logging:
      driver: none

  frontend:
    build:
      context: .
      dockerfile: docker/production/frontend.Dockerfile
    volumes:
      - ./frontend:/frontend:cached
      - node_modules:/frontend/node_modules
    command: yarn dev --port 3001 --host 0.0.0.0
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"

  # redis:
  #   image: redis:7.0.5
  #   restart: always

  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: docker/production/sidekiq.Dockerfile
  #   volumes:
  #     - ./backend:/sidekiq:cached
  #     - sidekiq_tmp:/sidekiq/tmp
  #     - bundle:/sidekiq/vendor
  #   ports:
  #     - "3002:3000"
  #   env_file:
  #     - ./backend/.env
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   depends_on:
  #     - db
  #     - redis

volumes:
  bundle:
  db_data:
  node_modules:
  backend_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
  sidekiq_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
