version: "3.9"

services:
  backend:
    image: ghcr.io/schoolofelvish/codeboard_backend:latest
    restart: always
    env_file:
      - ./backend/.env
    build:
      dockerfile: docker/production/backend.Dockerfile

  frontend:
    image: ghcr.io/schoolofelvish/codeboard_frontend:latest
    restart: always
    env_file:
      - ./frontend/.env
    build:
      context: .
      dockerfile: docker/production/frontend.Dockerfile

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codeboard_production
    logging:
      driver: none

volumes:
  bundle:
  db_data:
  node_modules:
  backend_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
  sidekiq_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
