version: "3.9"

services:
  backend:
    image: ghcr.io/schoolofelvish/codeboard_backend
    restart: always
    build:
      dockerfile: docker/production/backend.Dockerfile

  frontend:
    image: ghcr.io/schoolofelvish/codeboard_frontend
    restart: always
    build:
      context: .
      dockerfile: docker/production/frontend.Dockerfile

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  # redis:
  #   image: redis:7.0.5
  #   restart: always

  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: docker/development/sidekiq.Dockerfile
  #   volumes:
  #     - ./backend:/sidekiq:cached
  #     - sidekiq_tmp:/sidekiq/tmp
  #     - bundle:/sidekiq/vendor
  #   ports:
  #     - "3002:3000"
  #   env_file:
  #     - ./backend/.env
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   depends_on:
  #     - db
  #     - redis

volumes:
  bundle:
  db_data:
  node_modules:
  backend_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
  sidekiq_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
