services:
  backend:
    image: ghcr.io/schoolofelvish/codeboard_backend:latest
    volumes:
      - backend_tmp:/backend/tmp
    command: bin/rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    logging:
      driver: none

  frontend:
    image: ghcr.io/schoolofelvish/codeboard_frontend:latest
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
  backend_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000
