name: Delivery

on:
  workflow_run:
    workflows: CI
    branches: main
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Github Container Registry
      run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Fetch secrets from tawbar
      run: |
        curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./frontend/.env
        curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./frontend/.env

    - name: Build and Push Docker Images
      run: |
        docker compose -f docker-compose.yml -f production.yml build
        docker compose -f docker-compose.yml -f production.yml push

    - name: SSH into VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd ~/SchoolOfElvish/codeboard
          docker compose -f docker-compose.yml -f production.yml pull
          docker compose -f docker-compose.yml -f production.yml up -d
