name: Delivery

on: push

jobs:
  deploy:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Fetch secrets from tawbar
      run: |
        curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_FRONTEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_FRONTEND_API_KEY }}' -o ./frontend/.env
        curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./backend/.env

    - name: Build and push Docker images backend
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: docker/production/backend.Dockerfile
        tags: ghcr.io/schoolofelvish/codeboard_backend:latest

    - name: Build and push Docker images frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        file: docker/production/frontend.Dockerfile
        tags: ghcr.io/schoolofelvish/codeboard_frontend:latest

    - name: SSH into production VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd ~/SchoolOfElvish/codeboard
          docker compose -f production.yml pull
          docker compose -f production.yml up -d
